version: '2'

networks:
  app-minio:
    driver: bridge
services:

  minio:
    image: 'bitnami/minio:latest'
    volumes:
      - ./data:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=
      - MINIO_ROOT_PASSWORD=
    networks:
      - app-minio
